base/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.indexpage, name='home'),
    path('books', views.Bookview.as_view(), name='books'),
    path('books/<slug:slug>', views.Bookview.as_view(), name='books'),
    path('books/<str:add>', views.Bookview.as_view(), name='addbook'),
]

bookreader/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include(('base.urls', 'base'), namespace="base")),
    path('', include(('users.urls', 'users'), namespace="users")),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

base/models.py
from django.db import models
from django.utils.text import slugify


class BookModel(models.Model):
    genre = models.CharField(max_length=20)
    title = models.CharField(max_length=50)
    author = models.CharField(max_length=20)
    description = models.TextField()
    file = models.FileField(upload_to ='books')
    slug = models.SlugField(default="", null=False)

    def __str__(self):
        return f"{self.title} | {self.author}"

    def save(self, *args, **kwargs):
        self.slug = slugify(self.title.replace(' ', '-'))
        super().save(*args, **kwargs)

base/forms.py
from django import forms

from . import models


class BookForm(forms.ModelForm):
    class Meta:
        model = models.BookModel
        fields = ["genre", "title", "author", "description", "file"]

base/views.py
from django.core.files.storage import FileSystemStorage
from django.shortcuts import render, redirect
from django.urls import reverse_lazy
from django.views import View
from django.http import HttpResponse
from django.contrib.auth.mixins import LoginRequiredMixin

from . import models
from . import forms


def indexpage(request):
    return redirect(reverse_lazy("base:books"))

class Bookview(LoginRequiredMixin, View):

    def get(self, request, slug=None):
        if slug == "add":
            return render(request, "addbook.html")
        if slug is not None:
            return render(request, "book.html", context={"book": models.BookModel.objects.filter(slug=slug)[0]})
        return render(request, "books.html", context={"books": models.BookModel.objects.all()})

    def post(self, request, add=None):
        addbookform = forms.BookForm(request.POST, request.FILES)
        if addbookform.is_valid():
            addbookform.save()
        print(addbookform.errors)
        return redirect(reverse_lazy("base:books"))

base/templates/addbook.html
{% extends 'base.html' %}

{% block title %} Books {% endblock %}

{% block content %}
<div class="m-5">
    <form method="post" action="{% url 'base:books' %}" enctype="multipart/form-data">
        {% csrf_token %}


        
            <div class="row mb-3">
              <label for="inputEmail3" class="col-sm-2 col-form-label">Genre</label>
              <div class="col-sm-10">
                <input type="text" class="form-control" id="genre" name="genre">
              </div>
            </div>
            <div class="row mb-3">
                <label for="inputEmail3" class="col-sm-2 col-form-label">Title</label>
                <div class="col-sm-10">
                  <input type="text" class="form-control" id="title" name="title"> 
                </div>
              </div>
              <div class="row mb-3">
                <label for="inputEmail3" class="col-sm-2 col-form-label">Author</label>
                <div class="col-sm-10">
                  <input type="text" class="form-control" id="author" name="author">
                </div>
              </div>
              <div class="row mb-3">
                <label for="inputEmail3" class="col-sm-2 col-form-label">Description</label>
                <div class="col-sm-10">
                  <input type="text" class="form-control" id="description" name="description">
                </div>
              </div>
              <div class="row mb-3">
                <label for="inputEmail3" class="col-sm-2 col-form-label">Book</label>
                <div class="col-sm-10">
                  <input type="file" class="form-control" id="book" name="file">
                </div>
              </div>
            <button type="submit" class="btn btn-primary"> POST</button>
        


      
    </form>
</div>
{% endblock %}

base/templates/base.html
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">

    <link rel="stylesheet" href="{% static '/css/bootstrap.css' %}">
    <link rel="stylesheet" href="{% static 'css/styles.css' %}">
    <title>{% block title %}{% endblock %}</title>
</head>
<body style="background-color: gray;">
{% block content %}{% endblock %}
</body>

<script src="{% static 'js/script.js' %}"></script>
  
  <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.8/dist/umd/popper.min.js" integrity="sha384-I7E8VVD/ismYTF4hNIPjVp/Zjvgyol6VFvRkX/vR+Vc4jQkC+hVqc2pM8ODewa9r" crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.min.js" integrity="sha384-BBtl+eGJRgqQAUMxJ7pMwbEyER4l1g+O15P+16Ep7Q9Q+zqX6gSbd85u4mG4QzX+" crossorigin="anonymous"></script>
</html>

base/templates/book.html
{% extends 'base.html' %}

{% block title %} Book | {{ book.title }} {% endblock %}

{% block content %}

{% load static %}

<div class="card text-center m-5" >
    
    <h3 class="card-header">
        {{ book.genre }}
    </h3>
    <div class="card-body">
      <h5 class="card-title"> {{ book.title }}</h5>
      <h5 class="card-title"> {{ book.author }}</h5>
      <h5 class="card-title">{{ book.description }} </h5>
      <a href="{{ book.file.url }}" class="btn btn-primary btn-lg" style="width: 15rem;">READ</a>
    </div>
   
  </div>

        
{% endblock %}

base/templates/books.html
{% extends 'base.html' %}

{% block title %} Books {% endblock %}

{% block content %}
{% load static %}
    {% include 'shared_layout/navbar.html' %}

  <div class="carousel-inner">
    <div class="carousel-item active">
      <img src="{% static '/assets/lib1.jpg' %}" class="d-block w-100" style="height: 500px;" alt="...">
      <div class="carousel-caption d-none d-md-block">
        <h1 class="fw-bold">BOOKS</h1>
      </div>
      </div>
    </div>

  <div style="text-align: center; margin-top: 20px; margin-bottom: 30px;">
    
        <a href="{% url 'base:addbook' add='add' %}" class="btn btn-primary btn-lg" style="color: white; text-decoration: none;width: 70rem;">Add Book</a>
    
</div>


    {% for book in books %}
    

    <div class="container d-flex justify-content-center">
        <div class="card mb-3" style="max-width: 570px;">
            <div class="row g-0">
                <div class="col-md-4">
                    <img src="{% static '/assets/images.jpg' %}" class="img-fluid rounded-start" alt="...">
                </div>
                <div class="col-md-8">
                    <div class="card-body">
                        <h5 class="card-title text-uppercase font-weight-bold fw-bold">{{ book.genre }}</h5>
                        <h6 class="card-subtitle mb-2 text-muted">{{ book.title }}</h6>
                        <p class="card-text font-italic">By {{ book.author }}</p>
                        <p class="card-text">{{ book.description }}</p>
                        <!-- <a href="{% url 'base:books' slug=book.slug %}" class="btn btn-secondary btn-lg btn-block" style="width: 100%;">Details</a> -->
                        <a href="{{ book.file.url }}" class="btn btn-primary btn-lg btn-block mt-2" style="width: 100%;">READ</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
    
  
    
    
       
    {% endfor %}
    
{% endblock %}

base/templates/home.html
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>home</title>
</head>
<body>
    {% load static %}
    <img src="atic {% st'/assets/left-img.jpg' %}" class="card-img" style="" alt="...">
<h3>
    <a href="{% url 'books' %}">books</a>
</h3>
</body>
</html>