base/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.indexpage, name='home'),
    path('books', views.Bookview.as_view(), name='books'),
    path('books/<slug:slug>', views.Bookview.as_view(), name='books'),
    path('books/<str:add>', views.Bookview.as_view(), name='addbook'),
]

bookreader/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include(('base.urls', 'base'), namespace="base")),
    path('', include(('users.urls', 'users'), namespace="users")),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from .views import (
    home_view,
    login_view,
    logout_view,
    forgot_password_view,
    registeration_view,
    check_otp_view,
    check_reset_otp_view,
    reset_new_password_view,
)

app_name = 'users'

urlpatterns = [
    path('', home_view ,name='home'),
    path('login/', login_view, name='login'),
    path('logout/', logout_view, name='logout'),
    path('register/', registeration_view, name='register'),
    path('forgot-password/', forgot_password_view, name='forgot_password'),
    path('activate-email/', check_otp_view, name='activate_email'),
    path('reset-code/', check_reset_otp_view, name='reset_code'),
    path('new-password/', reset_new_password_view, name='reset_new_password'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)

base/models.py
from django.db import models
from django.utils.text import slugify


class BookModel(models.Model):
    genre = models.CharField(max_length=20)
    title = models.CharField(max_length=50)
    author = models.CharField(max_length=20)
    description = models.TextField()
    file = models.FileField(upload_to ='books')
    slug = models.SlugField(default="", null=False)

    def __str__(self):
        return f"{self.title} | {self.author}"

    def save(self, *args, **kwargs):
        self.slug = slugify(self.title.replace(' ', '-'))
        super().save(*args, **kwargs)

base/forms.py
from django import forms

from . import models


class BookForm(forms.ModelForm):
    class Meta:
        model = models.BookModel
        fields = ["genre", "title", "author", "description", "file"]

base/views.py
from django.core.files.storage import FileSystemStorage
from django.shortcuts import render, redirect
from django.urls import reverse_lazy
from django.views import View
from django.http import HttpResponse
from django.contrib.auth.mixins import LoginRequiredMixin

from . import models
from . import forms


def indexpage(request):
    return redirect(reverse_lazy("base:books"))

class Bookview(LoginRequiredMixin, View):

    def get(self, request, slug=None):
        if slug == "add":
            return render(request, "addbook.html")
        if slug is not None:
            return render(request, "book.html", context={"book": models.BookModel.objects.filter(slug=slug)[0]})
        return render(request, "books.html", context={"books": models.BookModel.objects.all()})

    def post(self, request, add=None):
        addbookform = forms.BookForm(request.POST, request.FILES)
        if addbookform.is_valid():
            addbookform.save()
        print(addbookform.errors)
        return redirect(reverse_lazy("base:books"))

templates/shared_layout/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <title>{%block title%}{%endblock title%}</title>
    {%block customcss%}
    {%endblock customcss%}
</head>
<body class="bg-light">
    {%include 'shared_layout/navbar.html'%}
    <div class="container my-3">
        {% if messages %}
        {% for message in messages %}
        <div class="alert alert-{%if message.tags == 'error'%}danger {%else%}{{message.tags}} {%endif%} my-2" role="alert">
            {{message}}
        </div>
        {% endfor %}
        {% endif %}

        {%block contents%}
        {%endblock contents%}
    </div>
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.6/umd/popper.min.js" integrity="sha384-wHAiFfRlMFy6i5SRaxvfOCifBUQy1xHdJ/yoi7FRNXMRBu5WHdZYu1hA6ZOblgut" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/js/bootstrap.min.js" integrity="sha384-B0UglyR+jN6CkvvICOB2joaf5I4l3gm9GU6Hc1og6Ls7i6U/mkkaduKaBhlAXv9k" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
    {%block customjs%}
    {%endblock customjs%}
</body>
</html>

templates/shared_layout/navbar.html
<nav class="navbar navbar-expand-lg navbar-dark bg-dark px-2">
    <a class="navbar-brand" href="{%url 'users:home'%}">BOOK READER</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav">
        {%if user.is_authenticated%}
        <li class="nav-item">
            <a class="nav-link" href="{%url 'users:logout'%}">Logout</a>
        </li>
        {%else%}
        <li class="nav-item">
            <a class="nav-link" href="{%url 'users:login'%}">Login</a>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="{%url 'users:register'%}">register</a>
        </li>
        {%endif%}
      </ul>
    </div>
  </nav>
  